module.exports = {
    Remove_all_filter: `(//a[@title='Remove All Filters'])[2]`,
    col_date_updated: `(//th[@scope='col']/following-sibling::th)[3]`,
    Edit_icon: `(//i[@placement='top-left'])[1]`,
    cwf_top_path: `//table[@class='table']/tbody[1]/tr[1]/td[2]`,
    Manage_peoples: `(//i[contains(@class,'fa fa-caret-left')]/following-sibling::a)[2]`,
    Manage_settings: `(//i[contains(@class,'fa fa-caret-left')]/following-sibling::a)[3]`,
    Manage_settings1: `(//i[contains(@class,'fa fa-caret-left')]/following-sibling::a)[2]`,
    Nav_CompanySetup1: `(//a[@data-pid='4'])[4]`,
    Nav_CompanySetup: `//a[contains(text(),'Company Setup')]`,
    Nav_ConfigurableWorkflow_CompanySetup: `//a[contains(text(),'Configurable Workflow')]`,
    Nav_ConfigurableWorkflow: `//*[@id="newui-header"]/div[2]/div[3]/div/div[2]/div/div/ul/li/ul/li[5]/ul/li[3]/a`,
    Nav_ConfigurableWorkflow2: `//*[@id="header"]/nav/div/div/div/div[3]/ul/li[4]/div/div/div/ul/li[5]/div/div/ul/li[3]/a`,
    Nav_ConfigurableWorkflow1: `//*[@id="header"]/nav/div/div/div/div[3]/ul/li[4]/div/div/div/ul/li[5]/div/div/ul/li[3]/a`,
    Nav_ConfigurableWorkflow3: `(//a[@data-pid='4'])[5]`,
    Tab_OtherSettings: `//a[@title='Other Settings']`,
    Dropdown_Default_workflow: `//*[@id="default_wf_allowed"]`,
    Button_submit: `//input[@type='submit']`,
    topHeader: `//h1[text()='Configurable Workflow']`,
    Create_Workflow_right: `//div[contains(@class,'col-6 btn-create')]//a[1]`,
    Create_popup: `//button[text()=' CREATE ']`,
    Input_WF_name: `//input[contains(@class,'form-control ng-pristine')]`,
    Input_WF_Description: `//label[text()='Description']/following::textarea`,
    Label_created: `//table[@class='table']/tbody[1]/tr[1]/td[2]`,
    Label_approved: `//table[@class='table']/tbody[1]/tr[3]/td[2]`,
    Label_denied: `//table[@class='table']/tbody[1]/tr[4]/td[2]`,
    row_wf_img: `(//tr[@class='first-row ng-star-inserted']//i)[3]`,
    Button_add_state_on_CWF_page: `a.btn.btn-save.ng-star-inserted`,
    Button_add_state_on_state_page: `//button[contains(@class,'btn btn-add')]`,
    path_Current_WF: `//div[@class='bread-crumb']//span[1]`,
    Button_cancel_state: `//button[contains(@class,'btn btn-add')]/following-sibling::button[1]`,
    Input_State_name: `//div[@class='form-group']//input[1]`,
    warning_CwfPage: `//a[@class='close ng-star-inserted']/following-sibling::div[1]`,
    Input_Transition_name: `//input[@placeholder='Name']`,
    RadioButton_yes: `//label[@for='yes0']`,
    RadioButton_yes1: `//label[@for='yes1']`,
    RadioButton_yes2: `//label[@for='yes2']`,
    a_Edit_Transition: `(//a[@ngbtooltip='Edit Transition'])[1]`,
    a_Delete_Transition: `(//a[@ngbtooltip='Duplicate Transition'])[1]`,
    Input_Right_Expression: `//input[@placeholder='Right Expression']`,
    Input_Right_Expression2: `(//input[@placeholder='Right Expression'])[2]`,
    Select_Left_Expression: `//select[@formcontrolname='left_exp']`,
    Select_Left_Expression2: `(//select[@formcontrolname='left_exp'])[2]`,
    Select_Operation: `//select[@formcontrolname='op']`,
    Select_Operation2: `(//select[@formcontrolname='op'])[2]`,
    Select_state2: `//div[@class='form-group']//select[1]`,
    Button_Save: `//button[@class='btn btn-add']/following-sibling::button[1]`,
    Select_who_allowed: `(//div[@class='border-danger']//span)[1]`
};