module.exports = {
    // url: 'https://app01-qa10.spotlighttms.com/app/',
    orderType: '#order_type',
    orderPurpose: '//*[@id="purpose"]',
    View_Cart_Checkout: 'text=View Cart and Checkout',
    View_Cart_Checkout_button: 'xpath=/html/body/app-root/div/app-header/header/nav/div/div/div/div/div[3]/ul/li[2]/app-cartmenu/div/div/div[2]/ul/li[1]/div/div/div[3]',
    Request: 'app-feature-box >> text=Request',
    CartIcon: '[aria-label="Shopping Cart"]',
    Submit: 'text=submit',
    add_no_of_ticket_by_1: 'xpath=/html/body/app-root/div/app-header/header/nav/div/div/div/div/div[3]/ul/li[2]/app-cartmenu/div/div/div[2]/ul/li[2]/div/div[2]/i[2]',
    EditQuantityAndGuest2: 'xpath=//*[@id="wizard-screens"]/div[1]/div/div[1]/button',
    EditQuantityAndGuest: 'text=EDIT QUANTITY AND GUESTS',
    AddGuest: `//button[text()=' ADD GUEST ']`,
    AddGuest2: 'text=ADD GUEST',
    NameInvitee: '[placeholder="Name"]',
    NameInvitee2: 'xpath=/html/body/ngb-modal-window/div/div/app-event-order-add-guest/div/div[2]/div/div[2]/app-dynamic-questions/div/div[1]/div/div/div/input',
    LocationInvitee: 'xpath=/html/body/ngb-modal-window/div/div/app-event-order-add-guest/div/div[2]/div/div[2]/app-dynamic-questions/div/div[1]/div/div/div/input',
    CompanyInvitee: 'xpath=/html/body/ngb-modal-window/div/div/app-event-order-add-guest/div/div[2]/div/div[2]/app-dynamic-questions/div/div[2]/div/div/div/input',
    EmailInvitee: 'xpath=/html/body/ngb-modal-window/div/div/app-event-order-add-guest/div/div[2]/div/div[2]/app-dynamic-questions/div/div[3]/div/div/input',
    TitleInvitee: '[placeholder="Title"]',
    PhoneInvitee: '[placeholder="Phone"]',
    AddToList: 'text=ADD TO LIST',
    CartOrderConfirmation: 'text=Cart Order Confirmation',
    LogoutButton: 'text=Logout',
    ApprovingManager: '[placeholder="Approving Manager"]',
    ApprovingManagerEmail: '[placeholder="Approving Manager Email"]',
    SearchBar: '[placeholder="Search a venue, team or performer"]',
    RequestButton: 'xpath=/html/body/app-root/div/app-search-result/div[2]/div/div[1]/div[1]/ngb-accordion/div[1]/div[2]/div/ul/li[1]/div/div[2]/a'
};