module.exports = {
    locators: {
        // url: 'https://app01-qa10.spotlighttms.com/',
        url: 'https://app1.spotlighttms.com/',
        username: 'input[name="username"]',
        password: 'input[name="password"]',
        loginButton: 'xpath=/html/body/app-root/div/app-login/div/div/div/form/div[4]',
        CustomerName: 'input[name="customerName"]',
        keepMeLoggedin: 'input[name="keepMeLogged"]',
        passwordError: 'body > app-root > div > app-login > div > div > div > form > div.input-group.has-danger > div',
        UsernameError: 'body > app-root > div > app-login > div > div > div > form > div.input-group.has-danger > div',
        ContinueButton: 'input[name="commit"]',
        LogOutHover1: `#dropdownMenuProfile > div > div > img`,
        LogOutHover2: `a#dropdownMenuProfile>div>div>img`,
        LogOutHover: `#user_dropdown_arrow > div`,
        LogOutHover_Standard_User: `#dropdownMenuProfile > div > div`,
        SSAHover2: `xpath=//*[@id="header"]/nav/div/div/div/div/div[3]/ul/li[4]/div/div/div/ul/li[2]/div/div/a`,
        SSAHover: `(//a[@id='1'])[1]`,
        SSAHover1: `#header > nav > div > div > div > div > div.col-6.col-md-3.col-lg-3.pl-0.pr-3.admin-sec.mt-2.d-block.ng-star-inserted > ul > li:nth-child(4) > div > div > div > ul > li:nth-child(2) > div > div > a`,
        CustomerFeatureListHover1: `#header > nav > div > div > div > div > div.col-6.col-md-3.col-lg-3.pl-0.pr-3.admin-sec.mt-2.d-block.ng-star-inserted > ul > li:nth-child(4) > div > div > div > ul > li:nth-child(2) > div > div > ul > li:nth-child(2) > a`,
        CustomerFeatureListHover: `(//a[@data-pid='1'])[2]`,
        CustomerFeatureListHover2: `xpath=//*[@id="header"]/nav/div/div/div/div/div[3]/ul/li[4]/div/div/div/ul/li[2]/div/div/ul/li[2]/a`,
        logoutClick: `#header > nav > div > div > div > div > div.col-6.col-md-3.col-lg-3.pl-0.pr-3.admin-sec.mt-2.d-block.ng-star-inserted > ul > li:nth-child(4) > div > div > div > button`,
        logoutClick_SU: `#header > nav > div > div > div > div > div.col-6.col-md-3.col-lg-3.pl-0.pr-3.admin-sec.mt-2.d-block.ng-star-inserted > ul > li:nth-child(3) > div > div > div > button`,
        DismisscardButton: `body > ngb-modal-window > div > div > app-company-policy > div > div > div.text-center > button`,
        DismisscardButton2: `xpath=/html/body/ngb-modal-window/div/div/app-company-policy/div/div/div[2]/button`,
        RadioBtnDoNotShow: `input[name="doNotShow"]`,
        DismissNotification1: `xpath=/html/body/div/div/button`,
        DismissButton: `text=Dismiss`,
        Final_sum: '',
        Final_records: '',
    },
};