module.exports = {
    locators: {
        CompanySetupUrl: 'https://app01-qa10.spotlighttms.com/customerFeatures/list',
        StubHubUrl: 'https://app01-qa10.spotlighttms.com/customerProfile/companySetup',
        HideExternalBit: 'xpath=/html/body/div[5]/div[4]/div/div[4]/div[2]/div[1]/div[2]/div[4]/div[3]/div[2]/div/div[2]/div/div[2]/table/tbody/tr[2]/td[9]',
        ticketTypeDropdown: '#dropdownMenu2 > span',
        selectMarketPlace: `(//button[@id='2'])[1]`,
        selectCompanyOwned: `(//button[@id='1'])[1]`,
        AllAvailableTickets: `(//button[@id='0'])[1]`,
        selectAllLocation: `(//button[@id='0'])[1]`,
        TextBuy: 'text=Buy',
        TextContinue: 'text=Continue',
        Searchevent: '[placeholder="Search a venue, team or performer"]',
        inlineFilter: 'input[name="inline_filter_value883"]',
        SelectInlineFilter: 'select[name="inline_filter_value888"]',
        SelectStubHub: 'select[name="stubhub"]',
        OrderType: 'select[name="order_type"]',
        selectOrderList: 'select[name="treq"]',
        ClickSaveContinue: 'text=Save and Continue',
        SelectPurpose: 'select[name="purpose"]',
        AddInvitee: 'text=Add Invitee',
        SelectUIAutomator: '#invitee-form >> text=UIAutomator',
        SelectTMAutomatorCSA: '#invitee-form >> text=TMAutomator CSA',
        SelectNoOfTickets: 'select[name="noTicket"]',
        OK_After_SelectNoOfTickets: '#invSave >> text=OK',
        OrderStatus: 'select[name="order_status"]',
        OrderNotDeny: '#midPanel > div > div.form > table.tablelist_static > tbody > tr:nth-child(3) > td > span:nth-child(2) > input',
        OrderDeny: 'xpath=/html/body/div[5]/form/div[2]/div/div[2]/table[3]/tbody/tr[3]/td/span[1]/input',
        B_ManagerApprovalOnly1: 'managerApprovalOnly',
        B_ManagerApprovalOnly: `input[name='managerApprovalOnly']`,
        B_ApprovalOrder: `input[value='Approve Order']`,
        TicketLeft: '#ticketsLeft',
        LinkTextOrderId: `//div[@class='col-lg-2 col-md-2']//a[1]`,
        DashboardBodyPath1: 'xpath=/html/body/app-root/div/app-home/div[3]',
        DashboardBodyPath: `//*[@id="skip-content-main-container"]`,
        IconAddItem: `//span[@title='Add']`,
        Submit: `//input[@type='submit']`
    },
};