on:
  push:
    branches:
    - test_sub_Brach  

jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, ubuntu-latest,, windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1     
      - name: Install dependencies 
        run: npm install && npx playwright install 
        
      - name: set Report Path
        run: SETX /M CUCUMBER_PUBLISH_TOKEN 793ed325-f0af-45c1-badf-1626d5507bea
        
      - name: Run_Tests
        id: Run_Tests
        run: npm test  
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result-report
          path: report/cucumber-html-report.html    
          
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3   #slack/webhook-action@master
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        with:
          channel: '#regression_job'
          username: UI_API_Automator_job
          text:  ${{join('Report has been Generated', '\n b jbvhjkghj')}} 
          status: success    
