on:
  schedule:
    - cron: "59 23 * * *"
  push:
    branches:
    - cwf_smoke

jobs: 
  e2e-tests:
    runs-on: windows-latest # or macos-latest, ubuntu-latest,, windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies 
        run: npm install && npx playwright install         
      - name: Run tests
        run: npm test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-result-report
          path: report/cucumber-html-report.html
#      - name: Cucumber Report to Annotations
#        uses: deblockt/cucumber-report-annotations-action@v1.7
#        with:
#          access-token: ${{ secrets.GITHUB_TOKEN }}
#          path: "**/cucumber-report.json"
